### ISSUE TITLE
Default (fallback) rule or match repo names with glob / regexp

### ISSUE THREAD

**Issue by olfway** [tumblr/docker-registry-pruner#4]
Thanks for the great tool, it looks really promisingly!

We have a lot of different repos in our registry and it's not possible to add a rule for each of them.

It would be really helpful to be able to specify default rule or match repo names with  glob/regexp

**Comment by byxorna** [comment]
Hey @olfway, thanks for the issue! I definitely thought long and hard about that feature when writing this tool - ultimately, I made the decision that I would prioritize explicit configuration over implicit, because I wanted to ensure the behavior of this tool was always well understood by end users. I wanted to guard against a seemingly benign rule from clobbering someones whole registry. For example, `repos: [".*"], keep_days: 3` could blow away an entire registry over a weekend, even though no repos were specifically earmarket for pruning. By making either `repos` or `labels` explicit, it requires a developer to opt in to this cleanup.

A potential workaround is to use `labels` to cleanup images regardless of repo, when a matching set of labels are set in the `Dockerfile` (i.e. `LABEL pruneme=true`. You can check out some examples of this at https://github.com/tumblr/docker-registry-pruner/blob/master/docs/config.md.

Please let me know if this works in your testing!

**Comment by olfway** [comment]
I understand your concerns, but imaging a repo with at least 20–30 images, it's impractical to add all of them to the config. Especially because it isn't a closed list and new images can be added daily.

Maybe the solution would be to apply just first matched rule to the image. This way it will be still possible to set specific parameters for the special images and at the end have a safety net like repos: [".*"], keep_versions: 15

**Comment by byxorna** [comment]
I understand how your use-case diverges from the use-case this tool was originally envisioned to deal with. I am happy to discuss implementation details of possible new features to support this new use-case, if you are interested. However, I do not have bandwidth to add this feature right now - if you are interested in taking a stab at a PR, though, that would be awesome!
